### ISSUE TITLE
Feature Request: Delete/Re-arrange Actions in Piston

### ISSUE THREAD

**Issue by robwheatley** [ady624/CoRE#56]
First off, what you have done so far is fantastic. I've been having a play and I'm loving it.

Now down to business:

Maybe I'm missing something, but I can't see a way to remove actions from a piston or an ability to re-order the actions I have. At the moment, I end up having to create a new piston to replace the one I want to change.

For example, I have a basic piston that triggers on a switch state change. I have added 1 action and then to that action added 1 too many "And then". I can't see how to delete the extra one.

In another example, I added an action to a trigger, then added another one (this was before I realised that I could add multiple 'actions' to a single one using the 'and then' feature). I couldn't see how to delete the extra action I created.

**Comment by ady624** [comment]
You remove an action by removing all devices from it - has to do with ST making hard links between the app and the selected devices, so I need the user to deselect those devices so that the link is removed, before I allow the action to be removed. Simply remove all devices from the action and tap Done, the action will go away on its own.

Reindexing actions is not supported due to the difficult nature of the ST app. But a webCoRE version will allow full modification of the piston in a web browser - much much faster stuff...

**Comment by robwheatley** [comment]
Thanks Andy.
